# Project information
site_name:   GeneticVariation.jl
site_description: Datastructures and algorithms for working with genetic variation.
site_author: The BioJulia Organisation
site_url: https://biojulia.github.io/GeneticVariation.jl/

# Repository
repo_url:  https://github.com/BioJulia/GeneticVariation.jl

# Copyright
copyright: Copyright (c) 2017 The BioJulia Organisation

# Documentation and theme
theme: material
docs_dir: 'build'

# Options
extra:
  author:
    github: BioJulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite
  - def_list

# Page tree
pages:
- Home: index.md
- IO:
    - VCF and BCF formatted files: io/vcf-bcf.md
- Mutation Counting: site_counting.md
- Genetic Diversity: diversity.md
- Contributing: contributing.md
